apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: {{ default "http" .Values.servicePortName }}
  selector:
    app: {{ .Release.Name }}